import Head from "next/head";
import { useRouter } from "next/router";

export default function Article() {
  const router = useRouter();
  // console.log(router.query);
  const { slug } = router.query;
  return (
    <div className="container">
      <Head>
        <title>{slug}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{slug}</h1>
      <p>Article Description</p>
    </div>
  );
}
