import Head from "next/head";

export default function BlogIndex() {
  return (
    <div className="container">
      <Head>
        <title>Blog - NEXTJS COURSE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Blog</h1>
      <p>This is the blog page</p>
    </div>
  );
}
