import Head from "next/head";

export default function About() {
  return (
    <div className="container">
      <Head>
        <title>ABOUT - NEXTJS COURSE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 style={{ color: "red" }}>About</h1>
      <p>This is the about page</p>
      <style global jsx>
        {`
          body {
            background: yellow;
            color: black;
          }
          h1 {
            font-family: sans-serif;
            font-size: 5rem;
          }
        `}
      </style>
    </div>
  );
}
