import Head from "next/head";

export default function About() {
  return (
    <div className="container">
      <Head>
        <title>ABOUT - NEXTJS COURSE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>About</h1>
      <p>This is the about page</p>
    </div>
  );
}
